[build]
  command = "npm run build && mkdir -p functions-build && cp -r client/public/* dist/ && esbuild functions/server.js --platform=node --packages=external --bundle --outfile=functions/server.js"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"